[package]
name = "patch"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
common = { path = "../common" }
windows = { workspace = true }
minhook-sys = "0.1"
paste = "1.0"
widestring = "1.2.1"
log = { workspace = true }
anyhow = { workspace = true }